using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace iHubAdminAPI.Models
{
    public class EnumModel
    {
        //public int Value { get; set; }
        public string Name { get; set; }
    }

    public enum EnumTables
    {
        iHub_Inventory_Products,
        iHub_Products,
        iH_Category_Product_Mapping,
        iH_Product_Attributes,
        iH_Menus,
        iH_Pincode_Location_Id_Mapping,
        iH_Product_Vendor_Mapping,
        iH_Products_Grouping,
        iH_RaffleCoupons,
        iH_Store_Keeper_Store_Unit_ID_Mapping,
        iH_Stores_Keeper,
        iH_Unit_Pincode_Mapping,
        iH_User_Address_Mapping,
        iHub_Application_Domain_Information,
        iHub_Attribute_Keys,
        iHub_Attribute_Value,
        iHub_Buy_N_Get_N_Master,
        iHub_Buyer_EMI_Configuration,
        iHub_Cash_back_Wallet_Transaction,
        iHub_Category_Attributes,
        iHub_Child_Offer_Buyer_Mapping,
        iHub_Child_Offer_Details,
        iHub_Wallet_Transaction,
        iMaster_Consignment_Status_Id_Details,
        iMaster_Inventory_Product_Status_Id_Details,
        iMaster_Ordered_Product_Booking_Type,
        iMaster_Ordered_Product_Status_Id_Details,
        iMaster_Product_Status_Id_Details,
        iHub_Child_Offer_Id_Order_Id_Mapping,
        iHub_Consignment_Transations,
        iHub_Consignments,
        iHub_EMI_Master_Data,
        iHub_EMI_Orders,
        iHub_Employee_Details,
        iHub_Help_Manual,

        iHub_Logistics,
        iHub_Manual_And_Role_Mapping,
        iHub_Parent_Child_Offer_Details,
        iHub_Parent_Offers_Details,
        iHub_Product_Attributes,
        iHub_Product_Ordered_Locations,
        iHub_Restricted_Sale_Products_Categories,
        iHub_Scheme_Paid_Amounts,
        iHub_Scheme_Wallet,
        iHub_Scheme_Wallet_Transactions,
        iHub_Schemes,
        iHub_Master_Buyer_Type,
        iHub_MegaDeals,
        iHub_Notifications,
        iHub_Offer_Based_On_Details,
        iHub_Offer_Id_Unit_Id_Mapping,
        iHub_Offer_Product_Price_Details,
        iHub_Offer_Products_Details,
        iHub_Offers,
        iHub_Offers_Mapping,
        iHub_Online_Failed_Transactions,
        iHub_Schemes_Orders,
        iHub_Unit_Class_Master,
        iHub_Unit_Stock_Configuratin_Leaf_Categories,
        iHub_Unit_Stock_Configuratin_Main_Categories,
        iHub_Unit_Stock_Configuratin_Products,
        iHub_Unit_Type_Details,
        iHub_Units_DC_WH_ST,
        iHub_Vendor_Category_Mapping,
        iHub_Vendor_Invoicing_Details,
        iHub_Vendors,
        CM_Coupons,
        iD_BottomLinks,
        iD_Bulk_Products_Cart,
        iD_Buyer_Delivery_Address,
        iD_Buyer_Orders,
        iD_Buyers,
        iD_Cart,
        ID_Directmenu,
        iD_Offer_Id_Order_Id_Mapping,
        iD_Order_Payments,
        iD_Ordered_Product_Details,
        iD_Raised_Bulk_Order_Product_Details,
        iD_Raised_Bulk_Orders,
        iD_Review_Likes_Dislikes,
        iD_Review_Ratings,
        iD_State_GST_Number,
        AspNetUsers,
        AspNetRoles,
        AspNetUserClaims,
        AspNetUserLogins,
        AspNetUserRoles,
        //iD_StoreKeeper_Sales,
        iD_Wishlist,
        iH_Address_Details,
        //iH_Bank_Details,
        iH_Banners,
        iH_Brands,
        iH_Buyer_Id_User_Id_Mapping,
        iH_Buyers,
        iH_Categories,
        iH_CategoryAttributes,
        iH_CounterFiles,
        iH_Customer_Requested_Products,
        iH_Customer_Special_Requested_Products,
        iH_DefaultMessages,
        iH_DeviceKeys,
        iH_HomePage_Products,
        iH_HSN_Code,
        iH_Inventory_Transactions,
        iH_Manage_StoreKeeper_Expanses,
        iH_Master_Locations,
        iH_Master_Pincodes,
        iH_Masters_Data,
        iD_Orders_Main,
        iD_Payment_Transactions,
        iHub_Old_EMI_Orders,
        //iH_Recently_Viewed_Products,        
        //CM_Coupon_User_Validations,
        iHub_Unit_Stock_Configurantion_Type,
        iD_HomePage

    }
}